// Practice/vue prc/vue webgame/7.틱택토/TableComponent.vue
<template>
    <table>
        <TrComponent v-for="(rowData, index) in tableData" 
        v-bind:key="index"
        v-bind:row-data="rowData" 
        v-bind:row-index="index" 
        >
        </TrComponent>
    </table>
</template>

<script>
import TrComponent from './TrComponent'

    export default{
        props:{
            tableData : Array,
        },
        components:{
            TrComponent,
        }
    }
</script>
<style>

</style>

// Practice/react prc/react webgame/7.ticTactoe/Table.jsx
import React from 'react'
import Tr from './Tr'

const Table = ({ tableData ,dispatch}) => {
  return (
    <table >
      <tbody>
      {Array(tableData.length).fill().map((tr, i)=>(<Tr  key={i} dispatch={dispatch} rowIndex={i} rowData={tableData[i]}/>))}
      </tbody>
    </table>
  )
}

export default Table
